import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import SettingsPage from "~/components/SettingsPage";
import Timer from "~/components/Timer";

export default function Home() {

  const [showSettings, setShowSettings] = useState(true)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col min-h-screen items-center justify-center text-center w-full pt-12 bg-[#30384b] text-[#eee]">
        {showSettings ? <SettingsPage /> : <Timer />}


      </main>
    </>
  );
}
